### ISSUE TITLE
upload fotky v dev env by mal fungovat?

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#188]
vracia mi 

```
Request URL:http://localhost:3000/gallery/pictures
Request Method:POST
Status Code:404 Not Found
```

vidim ze `postPictureHandler` v kode je.
 ine (GET) requesty funguju normalne, napr.

```
Request URL:http://localhost:3000/gallery/pictures?by=bbox&bbox=16.866760253906254,48.219182942479165,17.234802246093754,48.463815894066066
Request Method:GET
Status Code:200 OK
```

**Comment by petervojtek** [comment]
cely log:

```
[2017-08-21T13:20:47.057Z]  INFO: koa/14212 on Peters-MacBook-Pro.local:   <-- POST /gallery/pictures (req_id=ec8f1d5b-cbc7-49a7-8510-2eba9ec73311, req.remoteAddress=::1, req.remotePort=50249)
    POST /gallery/pictures HTTP/1.1
    host: localhost:3000
    connection: keep-alive
    content-length: 1119812
    accept: application/json
    origin: http://local.freemap.sk:8080
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
    authorization: Bearer 5Le5msybyQMneSUVszlEbX
    content-type: multipart/form-data; boundary=----WebKitFormBoundary1f22nqymZenWTM2t
    referer: http://local.freemap.sk:8080/?map=10/48.26994/16.86676&layers=T
    accept-encoding: gzip, deflate, br
    accept-language: en-US,en;q=0.8

  Error: spawn exiftran ENOENT
      at exports._errnoException (util.js:1026:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
      at onErrorNT (internal/child_process.js:366:16)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)

[2017-08-21T13:20:47.110Z]  WARN: koa/14212 on Peters-MacBook-Pro.local:   --> POST /gallery/pictures 404 53ms (req_id=ec8f1d5b-cbc7-49a7-8510-2eba9ec73311, duration=53, req.remoteAddress=::1, req.remotePort=50249, err.code=ENOENT)
    POST /gallery/pictures HTTP/1.1
    host: localhost:3000
    connection: keep-alive
    content-length: 1119812
    accept: application/json
    origin: http://local.freemap.sk:8080
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
    authorization: Bearer 5Le5msybyQMneSUVszlEbX
    content-type: multipart/form-data; boundary=----WebKitFormBoundary1f22nqymZenWTM2t
    referer: http://local.freemap.sk:8080/?map=10/48.26994/16.86676&layers=T
    accept-encoding: gzip, deflate, br
    accept-language: en-US,en;q=0.8
    --
    HTTP/1.1 404 Not Found
    HTTP/1.1 404 Not Found
    Access-Control-Allow-Origin: http://local.freemap.sk:8080
    Content-Type: text/plain; charset=utf-8
    Content-Length: 9
    Date: Mon, 21 Aug 2017 13:20:47 GMT
    Connection: keep-alive
    --
    Error: spawn exiftran ENOENT
        at exports._errnoException (util.js:1026:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
        at onErrorNT (internal/child_process.js:366:16)
        at _combinedTickCallback (internal/process/next_tick.js:102:11)
        at process._tickCallback (internal/process/next_tick.js:161:9)

```

**Comment by zdila** [comment]
mozno lepsi hack by bolo spravit shellovsky skript s nazvom exiftran a don implementovat bud to `cp` alebo nejaku nahradu `exiftranu` (vyuziva sa len bezstratove otacanie podla exifu).
