### ISSUE TITLE
zmeny v mape  - nastroj nezobrazuje ziadne changesety

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/freemap-v3-react#198]
```
index.js:42 error in mw dispatch or next call, probably in middlware/reducer/render fn: Error: Minified React error #109; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=t for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (index.js:6)
    at f._renderValidatedComponent (index.js:42)
    at f.performInitialMount (index.js:42)
    at f.mountComponent (index.js:42)
    at Object.mountComponent (index.js:20)
    at f.performInitialMount (index.js:42)
    at f.mountComponent (index.js:42)
    at Object.mountComponent (index.js:20)
    at Object.updateChildren (index.js:42)
    at m._reconcilerUpdateChildren (index.js:42)
```

**Comment by petervojtek** [comment]
mne sa uz ani nedari spustit dev webserver, pise mi:

```
/Users/peter/repos/freemap-v3-react/webpack.config.js:91
);
^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/peter/repos/freemap-v3-react/node_modules/webpack/bin/convert-argv.js:97:18)
```

**Comment by zdila** [comment]
> mne sa uz ani nedari spustit dev webserver

a pouzivas node 8?

**Comment by petervojtek** [comment]
> a pouzivas node 8?

nie, mam node 7. 
do buducnosti by malo svoje caro nieco taketo:
https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-packages-json

**Comment by zdila** [comment]
suhlasim. moses pridat :)
